# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_DRM_GCN_VI) += gcn-drm.o
obj-$(CONFIG_DRM_GCN_XFB_OBSERVER) += gcn-xfb-observer.o
obj-$(CONFIG_DRM_GCN_GX_MEM1_KUNIT_TEST) += gcn_gx_mem1_test.o

gcn-drm-y := gcn_drm_drv.o gcn_drm_trace.o
